### ISSUE TITLE
Potential Shared Vuln with 8chan

### ISSUE THREAD

**Issue by LandonPowell** [vichan-devel/vichan#216]
Someone told me you were the codebase they were forked from, so I thought you might want to know about this: https://github.com/ctrlcctrlv/infinity/issues/551

TL;DR XSS vuln on board rules pages for one of your forks. Probably not a vuln if only users with certain permissions are allowed to make boards, but still something which can be used to multiply the impact of an account compromise significantly. 

I'm not sure if it works on vichan too.

**Comment by czaks** [comment]
I don't think vichan is affected. The bug regards the static pages module. Static pages edition is typically limited to users that can be considered also having raw html posting permissions, so it's kind of a less of an issue. What is more, vichan backported only vichan markup (called "infinity" in code) in the static pages module, which is equivalent to posting markup, the bug is probably related to Markdown or HTMLPurifier.

**Comment by LandonPowell** [comment]
Yeah, I assumed as such.
