### ISSUE TITLE
Is there any way to allow external image uploads?

### ISSUE THREAD

**Issue by FHEDUEmil** [vichan-devel/vichan#250]
Hi, sorry if this sounds dumb, but I want to use a script that uploads images smaller than 3GB to one site, and larger files up to 5GB to another site, using this script:
![image](https://user-images.githubusercontent.com/22838750/29554279-84e40e5e-86ec-11e7-9a7c-a60ebbd9e215.png)

Is there some way to get vichan to use the externally uploaded files? If this is currently impossible, would this ever be implemented?

**Comment by ctrlcctrlv** [comment]
>Is there some way to get vichan to use the externally uploaded files? 

You can link to them via the embed mechanism. Since `$config['embed']` takes a URL and transforms it into your provided HTML, if a thumbnail or video player is provided, you can also embed that.

Vichan cannot take files uploaded by users and upload them to another site, however, and it is very unlikely that would ever be supported.

**Comment by FHEDUEmil** [comment]
Thank you! Don't know how I missed that, haha.
