### ISSUE TITLE
error when i log into mod.php

### ISSUE THREAD

**Issue by lojinb** [vichan-devel/vichan#288]
using default admin//password

Caught fatal error: Uncaught Error: Call to undefined function mcrypt_create_iv() in /var/www/html/vichan/inc/mod/auth.php:75Stack trace:#0 /var/www/html/vichan/inc/mod/auth.php(50): generate_salt()#1 /var/www/html/vichan/inc/mod/auth.php(95): crypt_password('password')#2 /var/www/html/vichan/inc/mod/pages.php(38): login('admin', 'password')#3 /var/www/html/vichan/mod.php(189): mod_login()#4 {main} thrown in /var/www/html/vichan/inc/mod/auth.php on line 75

**Comment by ctrlcctrlv** [comment]
First of all, from README.md,

>**It is the opinion of the vichan development team that no new vichan imageboards should be deployed, and other imageboard packages, such as lynxchan, used instead.**

However, your problem is easy to solve just by simple Googling, `Call to undefined function mcrypt_create_iv()`, your PHP installation is missing its mcrypt module, which is usually installed by default and is required. Many modules are required actually, see a list here: https://github.com/vichan-devel/vichan/wiki/FreeBSD

Just install php-mcrypt or whatever it's called on your OS.
