### ISSUE TITLE
Tor install

### ISSUE THREAD

**Issue by timmayy** [vichan-devel/vichan#311]
so im creating a board behind tor for the hell of it. i can create a new board but when trying to create a new post int he board i get:
" inet_pton(): Unrecognized address unix: "

**Comment by ctrlcctrlv** [comment]
For some reason your installation of PHP is passing malformed strings starting with `unix:` to vichan as the IP instead of an actual IP (e.g. 127.0.0.1 or ::1). Your server is misconfigured. Vichan is indeed installable over Tor but you're doing it wrong. Make sure PHP passes a valid dummy IP to be assigned to each post.
