### ISSUE TITLE
Names aren't colored on PHP 7.4

### ISSUE THREAD

**Issue by z0z0z** [vichan-devel/vichan#366]
After you upgrade to PHP 7.4 and rebuild all in the dashboard, names aren't colored or bold.

Going back to PHP 7.3 and rebuilding restores the name style.

![2020-01-20-174503_616x199_scrot](https://user-images.githubusercontent.com/12925873/72762740-a24ab080-3bd8-11ea-8230-0dab7aae2ea6.png)

**Comment by ctrlcctrlv** [comment]
Lol, this is probably related to the Twig-related part of https://github.com/vichan-devel/vichan/commit/a2ba03849f3adefa745838bff626c8304eb3d8c7. I'll try a few things.

**Comment by ctrlcctrlv** [comment]
It's not. I reverted back to https://github.com/vichan-devel/vichan/commit/af06cf37378806e7718a56a7a439b06bc4250514 and applied https://github.com/vichan-devel/vichan/commit/5e809047ad7427386e1507a52b7d050379013877 on top and it still happens. Sorry, I have no idea what's wrong, and don't want to spend any more time on the problem tracking it down.

**Comment by ctrlcctrlv** [comment]
I'm sorry. It's human nature that your brain doesn't stop thinking about a problem even when you try to tear yourself away. I've fixed it, but I don't know why the solution works. This software is ancient, and the problem is in a library. Wait for Github to automatically close issue after I push to see the fix

**Comment by z0z0z** [comment]
@ctrlcctrlv Thanks a lot, I know this frustrates you but I do appreciate it, as someone still running a vichan board.
