### ISSUE TITLE
(beta) Noted bugs that need to be fixed before next vichan stable release

### ISSUE THREAD

**Issue by RealAngeleno** [vichan-devel/vichan#580]
Leaving all bugs here that need to be fixed before the next vichan stable release. <s>Crossed out</s> means that it was fixed.

- <s>Dismiss Post works exactly the same as Dismiss+, dismissing all posts by the corresponding IP address.</s>
- <s>When it comes to reports of a post and its replies, reports for that thread get messed up (duplicated, mismatched, etc). Is fixed by dismissing one of the thread reports. #567</s>
- <s>User list causes error with twig.</s>
- <s>There is no space after the name (e.g. Anonymous06/05/2023 instead of Anonymous 06/05/2023).</s>
- <s>Rangebans are not functional.</s>
- <s>AJAX requests when it comes to deleting or reporting posts are not made.</s>

**Comment by ogjamesfranco** [comment]
For the spacing issue - it seems to be caused by one of the changes in #553, which replaced all instances of the "remove_whitespace" twig filter with twig's "spaceless" filter. The remove_whitespace filter only removed \t, \r, and \n characters, not spaces (see 427f3f8a0a8b301507d24f3392bcfd9c34b7d580), whereas I'm guessing twig's spaceless filter also removes space characters. If you try taking out the apply spaceless tags in post_thread.html, the described issue goes away.

I don't mind making a pull request to revert things to the old filter if you'd like, though I'm still familiarizing myself with the project and the frameworks/tools being used, so I'm not terribly confident in changing a ton of files without double-checking things first.

**Comment by RealAngeleno** [comment]
> For the spacing issue - it seems to be caused by one of the changes in #553, which replaced all instances of the "remove_whitespace" twig filter with twig's "spaceless" filter. The remove_whitespace filter only removed \t, \r, and \n characters, not spaces (see [427f3f8](https://github.com/vichan-devel/vichan/commit/427f3f8a0a8b301507d24f3392bcfd9c34b7d580)), whereas I'm guessing twig's spaceless filter also removes space characters. If you try taking out the apply spaceless tags in post_thread.html, the described issue goes away.
> 
> I don't mind making a pull request to revert things to the old filter if you'd like, though I'm still familiarizing myself with the project and the frameworks/tools being used, so I'm not terribly confident in changing a ton of files without double-checking things first.

There's defninitely no harm in reverting the changes you mentioned, and also didn't notice any issues when doing such.

**Comment by RealAngeleno** [comment]
Removing the spaceless filter during such portion is probably the best solution then.
