### ISSUE TITLE
5.2.0 -- Your request looks automated

### ISSUE THREAD

**Issue by RealAngeleno** [vichan-devel/vichan#766]
I haven't looked into it too much, but it appears to happen randomly, so could be an issue with the hidden fields shown for antispam.

**Comment by andrewwhiteingale** [comment]
+ to this. It happens when there is problem with SQL database. I don't know why.

**Comment by seisatsu** [comment]
This occasionally happens on my sites, no one can post for a while and then it clears up on its own.

**Comment by andrewwhiteingale** [comment]
But there might be also issue that I came across with missing json file like page2.json is missing when it shouldn't even be here. I thought it might be related to changing page amount as that's where the problem started. It caused me to delete the entire board. One biggest issue is that it refuses to rebuild with missing board files which can be problematic.

If it can't rebuild with missing html files then it is preferable that it rebuilds itself without it. Otherwise, it will lead to breaking the site. That, however can't be fixed quickly, I admit.

**Comment by perdedora** [comment]
This error appear when there's something wrong with antibot. Maybe the hidden fields expired when the user tried to post. 
Usually happens when I leave for a while and try to post without refreshing.

**Comment by RealAngeleno** [comment]
It's indeed a hash mismatch

**Comment by figamin** [comment]
This is also an issue on my site

**Comment by RealAngeleno** [comment]
I removed the entire system entirely since it made vichan bulky and spambots could get around it pretty easily anyways.
