### ISSUE TITLE
Vichan banned worldwide?

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#861]
How come vichan does not show up when one searches git for "imageboard"- that is unfair and infringing on the basic rights of the vichan repo. As such, it would seem that vichan software is illegal or something, and the vichan maintainers should do something about it. Together, we can save the internet and make imageboards great again! :)

**Comment by RealAngeleno** [comment]
Makes me wonder if it has something to do with vichan being a fork of tinyboard, and github not showing such.

**Comment by imageboardz** [comment]
@RealAngeleno this "Vichan" repo does not even show up when one searches "vichan", which is quite absurd. https://github.com/vichan-devel/ is clearly targeted and suppressed from search results, even though vichan is not doing anything wrong. Just thought I would remind people of the obvious reality that this repo  is experiencing for years so far.

**Comment by perdedora** [comment]
There's no conspiracy here. Forks do not appear on search results. If you search for Tinyboard is there.

**Comment by imageboardz** [comment]
@perdedora  wrong. a simple search of "vichan" results in OTHER things than vichan. Your mental gymnastics are not logical, and no user is expected to jump through the hoops in order to bring up vichan in the search results- something that OBVIOUSLY anyone who does not know what vichan is will ever do. I will let y'all go back to pretending that you are working on vichan now while you promise to keep it up to date - meanwhile it fails on 3 php versions lower than the latest. In other words, this repo is about 3 years behind. Good luck with that.

**Comment by imageboardz** [comment]
Can you ad a search feature to vichan that displays anything except the term searched for? That would be cool.
